### ISSUE TITLE
When the source code can be released?

### ISSUE THREAD

**Issue by XiruiTeng** [Kelvin-ywc/LPI#1]

**Comment by Kelvin-ywc** [comment]
Thank you for your feedback. The code for image-text retrieval is located in the retrieval folder, and the code for referring expression comprehension is in the grounding folder. Currently, the code only supports single-GPU execution; it will take some time to enable multi-GPU support.

**Comment by XiruiTeng** [comment]
> Thank you for your feedback. The code for image-text retrieval is located in the retrieval folder, and the code for referring expression comprehension is in the grounding folder. Currently, the code only supports single-GPU execution; it will take some time to enable multi-GPU support.

Thanks for you reply! I also find you are the author of the paper _Calibrating Prompt from History for Continual Vision-Language Retrieval and Grounding_. When will you release the code of this paper?
