### ISSUE TITLE
About Config

### ISSUE THREAD

**Issue by XiruiTeng** [Kelvin-ywc/LPI#2]
Thanks for your great work! After running your code, I found this /home1/yanweicai/DATA/CV/coco/annotations/retrieval_train2014.json file is needed. However, this file isn't in COCO14 dataset. Can you tell me how to obtain this file? Thanks a lot!

**Comment by Kelvin-ywc** [comment]
This is a preprocessed file based on the original annotations, which can be accessed through the following Baidu Cloud link: https://pan.baidu.com/s/17wD4O8OwQSeV4qgBAIX4qQ?pwd=f0yv
