### ISSUE TITLE
AttributeError: 'SliNet' object has no attribute 'visual_prompts'

### ISSUE THREAD

**Issue by XiruiTeng** [Kelvin-ywc/LPI#3]
Thanks for continuing to answer my question! Unfortunately, I still met some errors when running your code. 
1. In the file LPI/retrieval/main.py, your code mentions using the coco_sprompts.json to train LPI. So, what do your coco_lpi.json do? Is this a bug?
2. I used the coco_lpi.json to train lpi and I met this error "AttributeError: 'SliNet' object has no attribute 'visual_prompts'". This error occurs in LPI-main/retrieval/methods/sprompt.py", line 463.

**Comment by Kelvin-ywc** [comment]
Thank you for your feedback. I have updated the code, corrected some errors in the previous version, and provided further clarification on the retrieval task. 
(1) Regarding the first issue, we use coco_lpi.json to train our proposed model, while coco_sprompts.json is used for comparison experiments with the S-Prompts method. 
(2) For the second issue, running the updated code should resolve the problem. 
In the upcoming revision, I will provide further clarification on the grounding task.

**Comment by Kelvin-ywc** [comment]
> Thanks for continuing to answer my question! Unfortunately, I still met some errors when running your code.
> 
> 1. In the file LPI/retrieval/main.py, your code mentions using the coco_sprompts.json to train LPI. So, what do your coco_lpi.json do? Is this a bug?
> 2. I used the coco_lpi.json to train lpi and I met this error "AttributeError: 'SliNet' object has no attribute 'visual_prompts'". This error occurs in LPI-main/retrieval/methods/sprompt.py", line 463.

Thank you for your feedback. I have updated the code, corrected some errors in the previous version, and provided further clarification on the retrieval task.
(1) Regarding the first issue, we use coco_lpi.json to train our proposed model, while coco_sprompts.json is used for comparison experiments with the S-Prompts method.
(2) For the second issue, running the updated code should resolve the problem.
In the upcoming revision, I will provide further clarification on the grounding task.

**Comment by XiruiTeng** [comment]
> > Thanks for continuing to answer my question! Unfortunately, I still met some errors when running your code.
> > 
> > 1. In the file LPI/retrieval/main.py, your code mentions using the coco_sprompts.json to train LPI. So, what do your coco_lpi.json do? Is this a bug?
> > 2. I used the coco_lpi.json to train lpi and I met this error "AttributeError: 'SliNet' object has no attribute 'visual_prompts'". This error occurs in LPI-main/retrieval/methods/sprompt.py", line 463.
> 
> Thank you for your feedback. I have updated the code, corrected some errors in the previous version, and provided further clarification on the retrieval task. (1) Regarding the first issue, we use coco_lpi.json to train our proposed model, while coco_sprompts.json is used for comparison experiments with the S-Prompts method. (2) For the second issue, running the updated code should resolve the problem. In the upcoming revision, I will provide further clarification on the grounding task.

Thank you very much!
